export const heroSectionStyles = {
  width: "100%",
  minHeight: "100vh",
  height: "100vh", // Ensures full viewport height
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  position: "relative",
  overflow: "hidden", // Ensures background stays inside
  zIndex: 1,
  px: 2, // Responsive horizontal padding
  boxSizing: "border-box",
  overflowX: "hidden",
};

export const aboutSectionStyles = {
  width: "100vw",
  minHeight: "100vh",
  height: "100vh",
  background: "radial-gradient(circle at 22% 18%, #332116 0%, #170e09 42%, #0b0705 100%)",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  color: "#f8efe4",
  py: 0,
  position: "relative",
  overflow: "hidden",
  "@keyframes coffeeDrift": {
    "0%": { transform: "translateY(0px) translateX(0px)", opacity: 0.25 },
    "50%": { transform: "translateY(-24px) translateX(12px)", opacity: 0.45 },
    "100%": { transform: "translateY(0px) translateX(0px)", opacity: 0.25 },
  },
  "@keyframes coffeeGlow": {
    "0%": { transform: "scale(1)", opacity: 0.2 },
    "50%": { transform: "scale(1.08)", opacity: 0.35 },
    "100%": { transform: "scale(1)", opacity: 0.2 },
  },
  "&::before": {
    content: '""',
    position: "absolute",
    inset: "-10% -20% auto auto",
    width: "42vw",
    height: "42vw",
    maxWidth: "520px",
    maxHeight: "520px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(200,145,94,0.34) 0%, rgba(200,145,94,0) 72%)",
    filter: "blur(14px)",
    animation: "coffeeGlow 8.5s ease-in-out infinite",
    pointerEvents: "none",
  },
  "&::after": {
    content: '""',
    position: "absolute",
    left: "-8%",
    bottom: "-14%",
    width: "36vw",
    height: "36vw",
    maxWidth: "460px",
    maxHeight: "460px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(142,95,57,0.34) 0%, rgba(142,95,57,0) 74%)",
    filter: "blur(16px)",
    animation: "coffeeDrift 10s ease-in-out infinite",
    pointerEvents: "none",
  },
  "@media (max-width:900px)": {
    "&::before": { width: "62vw", height: "62vw", opacity: 0.8 },
    "&::after": { width: "52vw", height: "52vw", opacity: 0.8 },
  },
};
